### PR TITLE
[WIP] Better errors.

### PR DESCRIPTION
**Pull request by jMyles**

### CODE REVIEW

**Comment by tuxxy** [comment]
Status on this? Are we going to drop this PR or what's happening?

**Comment by jMyles** [comment]
Probably drop, but give me a few hours to mull it over.

**Comment by tuxxy** [comment]
Sure, take your time. It can always be reopened.

**Comment by jMyles** [comment]
OK yeah, this is an obvious drop, but I'm not ready to call it wontfix because I think that it is still a good idea to have a better error than "Generic Umbral Error" in the event that Bob doesn't have enough CFrags.

**Pull request closed without merging**
